name: Lint, test, and upload codecov

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: snok/.github/workflows/linting@main
  test:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.0-rc.1
      - uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-cache-0
      - uses: snok/install-poetry@v1.2.0-rc1
        with:
          virtualenvs-in-project: true
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: ${{ hashFiles('**/poetry.lock') }}-1
      - run: |
          poetry cache clear . --all
          poetry install --no-interaction --no-root
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: source $VENV && pytest main_tests.py --cov-report=xml
      - uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
