name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    name: "pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install pre-commit

      - uses: actions/cache@v3
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: key-0

      - run: pre-commit run --all-files

  test:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-cache-1

      - uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - uses: actions/cache@v3
        id: cache-venv
        with:
          path: .venv
          key: ${{ hashFiles('**/poetry.lock') }}-2

      - run: |
          pip install pyparsing==2.4.7
          poetry install --no-interaction --no-root
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - run: source $VENV && pytest --cov-report=xml

      - uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
